### ISSUE TITLE
GraalVM 21 native-image compilation 

### ISSUE THREAD

**Issue by dainiusjocas** [dainiusjocas/lucene-grep#27]
When compiled without Lucene quarkus extension: 
- Compilations succeeds
- Exception at runtime

```
✗ make build
clojure -M:native
Compiling lmgrep.cli
Compiling lmgrep.core
Compiling lmgrep.fs
Compiling lmgrep.grep
Compiling lmgrep.lucene
[lmgrep:769177]    classlist:   3,196.36 ms,  1.18 GB
[lmgrep:769177]        (cap):     515.88 ms,  1.18 GB
[lmgrep:769177]        setup:   1,928.48 ms,  1.18 GB
[lmgrep:769177]     (clinit):     623.88 ms,  2.72 GB
[lmgrep:769177]   (typeflow):  17,160.38 ms,  2.72 GB
[lmgrep:769177]    (objects):  12,770.39 ms,  2.72 GB
[lmgrep:769177]   (features):   1,214.95 ms,  2.72 GB
[lmgrep:769177]     analysis:  32,817.79 ms,  2.72 GB
[lmgrep:769177]     universe:   2,403.92 ms,  2.72 GB
[lmgrep:769177]      (parse):   5,801.50 ms,  2.72 GB
[lmgrep:769177]     (inline):  10,977.66 ms,  3.26 GB
[lmgrep:769177]    (compile):  50,000.95 ms,  4.44 GB
[lmgrep:769177]      compile:  69,816.24 ms,  4.44 GB
[lmgrep:769177]        image:   4,027.30 ms,  4.44 GB
[lmgrep:769177]        write:     719.09 ms,  4.44 GB
[lmgrep:769177]      [total]: 115,119.38 ms,  4.44 GB
➜  lucene-grep git:(main) ✗ ./lmgrep "test" README.md 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.ClassCastException: java.lang.invoke.BoundMethodHandle$Species_L cannot be cast to java.lang.invoke.SimpleMethodHandle
        at com.oracle.svm.methodhandles.MethodHandleIntrinsic.execute(MethodHandleIntrinsic.java:254)
        at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:80)
        at java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:74)
        at java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:981)
        at java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:958)
        at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:171)
        at java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
        at java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
        at org.apache.lucene.util.AttributeFactory$1.createInstance(AttributeFactory.java:148)
        at org.apache.lucene.util.AttributeFactory$StaticImplementationAttributeFactory.createAttributeInstance(AttributeFactory.java:111)
        at org.apache.lucene.util.AttributeSource.addAttribute(AttributeSource.java:213)
        at org.apache.lucene.analysis.standard.StandardTokenizer.<init>(StandardTokenizer.java:132)
        at beagle.text_analysis$tokenizer.invokeStatic(text_analysis.clj:51)
        at beagle.text_analysis$analyzer_constructor$fn__1377.invoke(text_analysis.clj:67)
        at beagle.text_analysis.proxy$org.apache.lucene.analysis.Analyzer$ff19274a.createComponents(Unknown Source)
        at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:136)
        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:199)
        at org.apache.lucene.document.Field.tokenStream(Field.java:513)
        at org.apache.lucene.index.memory.MemoryIndex.addField(MemoryIndex.java:380)
        at org.apache.lucene.monitor.DocumentBatch$SingletonDocumentBatch.<init>(DocumentBatch.java:112)
        at org.apache.lucene.monitor.DocumentBatch$SingletonDocumentBatch.<init>(DocumentBatch.java:105)
        at org.apache.lucene.monitor.DocumentBatch.of(DocumentBatch.java:60)
        at org.apache.lucene.monitor.Monitor.match(Monitor.java:256)
        at org.apache.lucene.monitor.Monitor.match(Monitor.java:276)
        at lmgrep.lucene$match_text.invokeStatic(lucene.clj:34)
        at lmgrep.lucene$match_monitor.invokeStatic(lucene.clj:78)
        at lmgrep.lucene$highlighter$fn__1730.invoke(lucene.clj:89)
        at lmgrep.grep$match_lines.invokeStatic(grep.clj:75)
        at lmgrep.grep$grep$fn__1671.invoke(grep.clj:97)
        at lmgrep.grep$grep.invokeStatic(grep.clj:97)
        at lmgrep.core$_main.invokeStatic(core.clj:21)
        at lmgrep.core$_main.doInvoke(core.clj:12)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at lmgrep.core.main(Unknown Source)
```

**Comment by Jolanta3109** [comment]
Build on `Linux think 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

[lmgrep-jol223.zip](https://github.com/dainiusjocas/lucene-grep/files/5937519/lmgrep-jol223.zip)

**Comment by dainiusjocas** [comment]
```
sudo dnf install gcc glibc-devel zlib-devel libstdc++-static
```
[lmgrep-dj.zip](https://github.com/dainiusjocas/lucene-grep/files/5937533/lmgrep-dj.zip)

**Comment by dainiusjocas** [comment]
https://github.com/oracle/graal/issues/394

**Comment by dainiusjocas** [comment]
built on ubuntu in docker static 
[lmgrep-ubuntu-docker.zip](https://github.com/dainiusjocas/lucene-grep/files/5937552/lmgrep-ubuntu-docker.zip)

**Comment by dainiusjocas** [comment]
[Uploading lmgrep-ubuntu.zip…]()
