### ISSUE TITLE
[Bug] Exception when misusing hyperlink

### ISSUE THREAD

**Issue by michelcaradec** [dainiusjocas/lucene-grep#92]
First of all, let me thank you for this tool.
I just discovered it few days ago, and it is really helpful.

The execution of this command:

```bash
echo "this will generate an exception" | lmgrep "exception" --hyperlink
```

Generates an exception:

```raw
Exception in thread "async-thread-macro-1" java.lang.NullPointerException
	at lmgrep.formatter$file_string.invokeStatic(formatter.clj:39)
	at lmgrep.formatter$string_output.invokeStatic(formatter.clj:59)
	at lmgrep.grep$matcher_fn$fn__11355.invoke(grep.clj:54)
	at clojure.core$map$fn__5880$fn__5881.invoke(core.clj:2746)
	at clojure.core.async.impl.channels$chan$fn__3302.invoke(channels.clj:300)
	at clojure.core.async.impl.channels.ManyToManyChannel.put_BANG_(channels.clj:143)
	at clojure.core.async$fn__7869.invokeStatic(async.clj:172)
	at clojure.core.async$pipeline_STAR_$process__8053.invoke(async.clj:531)
	at clojure.core.async$pipeline_STAR_$fn__8183.invoke(async.clj:549)
	at clojure.core.async$thread_call$fn__7976.invoke(async.clj:484)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

Thank you.

Version: v2021.04.26
Package: lmgrep-v2021.04.26-linux-amd64.zip

**Comment by dainiusjocas** [comment]
@michelcaradec, thanks for trying lmgrep! The bug will be fixed soon.

**Comment by dainiusjocas** [comment]
@michelcaradec the fix is released https://github.com/dainiusjocas/lucene-grep/releases/tag/v2021.05.02
